### ISSUE TITLE
Circular imports error

### ISSUE THREAD

**Issue by hunter-meloche** [kyb3r/emergent#11]
Hi, I just installed this with pip, but I'm getting this error when I try to use it.
```
AttributeError: partially initialized module 'emergent' has no attribute 'ChatAgent' (most likely due to a circular import)
```

I'd really appreciate it if someone could help me out. I'm using Python 3.11 for reference.

**Comment by kyb3r** [comment]
Did you install via: `pip install git+https://github.com/kyb3r/emergent`

**Comment by hunter-meloche** [comment]
That's correct. I tried making a venv and still had the same issue. I've yet to try with a different version of Python.

**Comment by hunter-meloche** [comment]
I realized I'm just using it wrong.
