### ISSUE TITLE
Max token limit breached when ending conversation

### ISSUE THREAD

**Issue by hunter-meloche** [kyb3r/emergent#13]
I had a lengthy discussion with GPT using Emergent (great job btw) and fed it small segments of a story I'm writing, but when saving its memories to json, I got the error response from the OpenAI API that I broke the token limit. The discussion itself was fine; it wasn't until `agent.end_conversation(memory_path)` was called that I had issues with the token limit.
```
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4940 tokens. Please reduce the length of the messages.
```
Adding some sort of token limit handler would be great. Please let me know if I'm doing something wrong, lol.

**Comment by hunter-meloche** [comment]
I implemented a solution that will help in some cases. https://github.com/kyb3r/emergent/pull/14

**Comment by kyb3r** [comment]
Thank you, merged :)

**Comment by hunter-meloche** [comment]
No problem at all. I was working towards creating something like this myself. Very happy people like you and Shapiro are laying out the groundwork hahaha
